server:
    port: 8080

spring:
    application:
        name: digital-banking

    datasource:
        url: jdbc:mysql://localhost:3306/digital-banking-db
        username: dev
        password: password

    jpa:
        hibernate:
            ddl-auto: update
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true